-- Generate data for the database

-- Generate warehouses
INSERT INTO warehouses (name, location, address, postcode, country, contact_name, contact_email, contact_phone)
VALUES ('Solar warehouse', 'Amsterdam', 'Amsterdamseweg 1', '1111AA', 'The Netherlands', 'John Doe', 'jane@gmail.com',
        '0612345678'),
       ('Lunar warehouse', 'Rotterdam', 'Rotterdamseweg 2', '2222BB', 'The Netherlands', 'Jane Doe', 'john@gmail.com',
        '0712345678'),
       ('Star warehouse', 'The Hague', 'Haagseweg 3', '3333CC', 'The Netherlands', 'Jim Doe', 'jim@gmail.com',
        '0812345678'),
       ('Galaxy warehouse', 'Utrecht', 'Utrechtseweg 4', '4444DD', 'The Netherlands', 'Jill Doe', 'jill@gmail.com',
        '0912345678');

-- Generate product categories
INSERT INTO product_categories (name, description)
VALUES ('Solar panel',
        'A solar panel is a panel designed to absorb the sun"s rays as a source of energy for generating electricity or heating.'),
       ('Solar inverter',
        'A solar inverter, or PV inverter, converts the variable direct current (DC) output of a photovoltaic (PV) solar panel into a utility frequency alternating current (AC).'),
       ('Solar battery',
        'A solar battery is a rechargeable battery that integrates a solar cell with battery power storage.'),
       ('Solar charge controller',
        'A solar charge controller, or solar regulator, is an electronic device that prevents batteries from overcharging.'),
       ('Solar mounting system',
        'A solar mounting system is used to fix solar panels on surfaces like roofs, building facades, or the ground.'),
       ('Solar cable', 'A solar cable is the interconnection cable used in photovoltaic power generation.'),
       ('Solar connector', 'A solar connector is an electrical connector designed to connect solar panels.');

-- Generate products
INSERT INTO Products (name, description, category_id)
VALUES ('Solar Panel 100W', '100W Solar Panel for generating electricity',
        (SELECT id FROM product_categories WHERE name = 'Solar panel')),
       ('Solar Panel 200W', '200W Solar Panel for generating electricity',
        (SELECT id FROM product_categories WHERE name = 'Solar panel')),
       ('Solar Panel 300W', '300W Solar Panel for generating electricity',
        (SELECT id FROM product_categories WHERE name = 'Solar panel')),
       ('Solar Panel 400W', '400W Solar Panel for generating electricity',
        (SELECT id FROM product_categories WHERE name = 'Solar panel')),
       ('Solar Inverter 500W', '500W Solar Inverter for converting DC to AC',
        (SELECT id FROM product_categories WHERE name = 'Solar inverter')),
       ('Solar Inverter 600W', '600W Solar Inverter for converting DC to AC',
        (SELECT id FROM product_categories WHERE name = 'Solar inverter')),
       ('Solar Inverter 700W', '700W Solar Inverter for converting DC to AC',
        (SELECT id FROM product_categories WHERE name = 'Solar inverter')),
       ('Solar Inverter 800W', '800W Solar Inverter for converting DC to AC',
        (SELECT id FROM product_categories WHERE name = 'Solar inverter')),
       ('Solar Battery 200Ah', '200Ah Solar Battery for storing electricity',
        (SELECT id FROM product_categories WHERE name = 'Solar battery')),
       ('Solar Battery 300Ah', '300Ah Solar Battery for storing electricity',
        (SELECT id FROM product_categories WHERE name = 'Solar battery')),
       ('Solar Battery 400Ah', '400Ah Solar Battery for storing electricity',
        (SELECT id FROM product_categories WHERE name = 'Solar battery')),
       ('Solar Battery 500Ah', '500Ah Solar Battery for storing electricity',
        (SELECT id FROM product_categories WHERE name = 'Solar battery')),
       ('Solar Charge Controller 20A', '20A Solar Charge Controller for controlling charge',
        (SELECT id FROM product_categories WHERE name = 'Solar charge controller')),
       ('Solar Mounting System', 'Solar Mounting System for mounting solar panels',
        (SELECT id FROM product_categories WHERE name = 'Solar mounting system')),
       ('Solar Cable 10m', '10m Solar Cable for connecting solar components',
        (SELECT id FROM product_categories WHERE name = 'Solar cable')),
       ('Solar Connector', 'Solar Connector for connecting solar panels',
        (SELECT id FROM product_categories WHERE name = 'Solar connector'));

-- Generate teams
INSERT INTO teams (name, warehouse_id)
VALUES ('Solar Warriors', 1),
       ('Solar Legends', 2),
       ('Solar Heroes', 3),
       ('Solar Champions', 4),
       ('Lunar Amazonians', 2),
       ('Lunar Spartans', 2),
       ('Lunar Titans', 2),
       ('Lunar Gods', 2),
       ('Star Jupiter', 3),
       ('Star Saturn', 3),
       ('Star Mars', 3),
       ('Star Venus', 3),
       ('Galaxy Andromeda', 4),
       ('Galaxy Milky Way', 4),
       ('Galaxy Black Hole', 4),
       ('Galaxy Big Bang', 4);

-- Generate users
INSERT INTO users (email, password, role, team_id)
VALUES ('admin@admin.com', 'admin', 'admin', 1),
       ('user1@user.com', 'user', 'User', 1),
       ('user2@user.com', 'password1', 'User', 1),
       ('user3@user.com', 'password2', 'User', 1),
       ('user4@user.com', 'password3', 'User', 1),
       ('user5@user.com', 'password4', 'User', 2),
       ('user6@user.com', 'password5', 'User', 2),
       ('user7@user.com', 'password6', 'User', 2),
       ('user8@user.com', 'password7', 'User', 3),
       ('user9@user.com', 'password8', 'User', 3),
       ('user10@user.com', 'password9', 'User', 3),
       ('user11@user.com', 'password10', 'User', 4),
       ('user12@user.com', 'password11', 'User', 4),
       ('user13@user.com', 'password12', 'User', 4),
       ('user14@user.com', 'password13', 'User', 5),
       ('user15@user.com', 'password14', 'User', 5),
       ('user16@user.com', 'password15', 'User', 5),
       ('user17@user.com', 'password16', 'User', 6),
       ('user18@user.com', 'password17', 'User', 6),
       ('user19@user.com', 'password18', 'User', 6),
       ('user20@user.com', 'password19', 'User', 7),
       ('user21@user.com', 'password20', 'User', 7),
       ('user22@user.com', 'password21', 'User', 7),
       ('user23@user.com', 'password22', 'User', 8),
       ('user24@user.com', 'password23', 'User', 8),
       ('user25@user.com', 'password24', 'User', 8),
       ('user26@user.com', 'password25', 'User', 9),
       ('user27@user.com', 'password26', 'User', 9),
       ('user28@user.com', 'password27', 'User', 9),
       ('user29@user.com', 'password28', 'User', 10),
       ('user30@user.com', 'password29', 'User', 10),
       ('user31@user.com', 'password30', 'User', 10),
       ('user32@user.com', 'password31', 'User', 11),
       ('user33@user.com', 'password32', 'User', 11),
       ('user34@user.com', 'password33', 'User', 11),
       ('user35@user.com', 'password34', 'User', 12),
       ('user36@user.com', 'password35', 'User', 12),
       ('user37@user.com', 'password36', 'User', 12),
       ('user38@user.com', 'password37', 'User', 13),
       ('user39@user.com', 'password38', 'User', 13),
       ('user40@user.com', 'password39', 'User', 13),
       ('user41@user.com', 'password40', 'User', 14),
       ('user42@user.com', 'password41', 'User', 14),
       ('user43@user.com', 'password42', 'User', 14),
       ('user44@user.com', 'password43', 'User', 15),
       ('user45@user.com', 'password44', 'USER', 15),
       ('user46@user.com', 'password45', 'User', 15),
       ('user47@user.com', 'password46', 'User', 16),
       ('user48@user.com', 'password47', 'User', 16),
       ('user49@user.com', 'password48', 'User', 16);
